config/routes.rb
Rails.application.routes.draw do
  # User Routes

  get '/signup' => 'users#new'
  get '/users' => 'users#index'
  post '/users' => 'users#create'

  # Session Routes
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
  root to: "landings#index"

  get '/reviews' => 'reviews#index'
  resources :products do
    resources :reviews
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :cost, presence: true
  validates :country_of_origin, presence: true

  before_save(:titleize_product)
  
  private
  def titleize_product
    self.name = self.name.titleize
  end
  
  scope :three_most_recent, -> { order(created_at: :desc).limit(5)}

  scope :most_reviews, -> {(
    select("products.id, products.name, products.country_of_origin, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
  )}

  scope :search, -> (country_of_origin_parameter) { where("country_of_origin like ?", "%#{country_of_origin_parameter}%")}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :author, presence: true
  validates :content_body, presence: true
  validates :rating, presence: true
  validates :content_body, length: { minimum: 50 }
  validates :content_body, length: { maximum: 250 }
  validates :rating, numericality: { greater_than: 0}
  validates :rating, numericality: { less_than: 6}
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def authorize
    if !current_user
      flash[:alert] = "You aren't authorized to visit that page."
      redirect_to '/'
    end
  end
  
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
    @products = Product.all 
    render :index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :only => [:new, :edit, :create, :destroy, :update] do
    redirect_to products_path unless current_user && current_user.admin
  end

  def index
    @products = Product.all 
    render :index
  end

  def new
    @product = Product.new
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:id])
    render :show
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else 
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :cost, :country_of_origin)
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authorize, except: [:index]

  def index
    @reviews = Review.all 
    render :index
  end

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = Review.new(review_params)
    if @review.save
      redirect_to product_path(@product)
    else 
      render :new
    end
  end

  def show
    @review = Review.find(params[:id])
    @product = Product.find(params[:product_id])
  end

  private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating, :product_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    render :index
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You've successfully signed up!"
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing up."
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/landings/index.html.erb
<div class="jumbotron">
  <h1> Mario's Foods</h1>
</div>
<div class="row">
  
  <h4>Check out some of our most recent items!</h4>
  <ul>
    <% Product.three_most_recent.each do |product| %>
    <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
  
  <h4>This is our current most popular item! (based on number of reviews):</h4>
  <ul>
  <%  Product.most_reviews.each do |product| %>
    <li><%= link_to product.name, product_path(product) %></li>
  <% end  %>
  </ul>
  


  <h4>These are the items we currently carry that are made in the USA!:</h4>
  <ul>
  <% Product.search("United States").each do |product| %>
    <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
  </ul>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :cost %>
  <%= f.text_field :cost %>
  <%= f.label :country_of_origin %>
  <%= f.text_field :country_of_origin %>
  <%= f.submit %>
<% end %> 

app/views/layouts/_review_form.html.erb
<%= render "layouts/errors", :object => @review %>


<%= form_for [@product, @review] do |f| %>
<% if params[:product_id] %>
<p>if statement test</p>
<input type="hidden" id="product_id" name="review[product_id]" value='<%="#{params[:product_id]}"%>'>
<% end %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_area :content_body %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <p><%= f.submit %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mario's Specialty Foods</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="container-test" class="container">
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          <nav class="navbar navbar-light bg-light">
            <a class="navbar-brand" href="/">Home</a>
            <a class="navbar-brand" href="/products">Products</a>
          </nav>
          <% if current_user %>
            <%= current_user.email %> | <%= link_to "Sign out", '/signout' %>
          <% else %>
            <%= link_to "Sign up", '/signup' %> | <%= link_to "Sign in", '/signin' %>
          <% end %>
          <%= flash[:alert] %>
          <%= flash[:notice] %>
          <%= yield %>
          <%= image_tag('vegetable.png') %>
        </div>
        <div class="col-md-2"></div>
      </div>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<div class="jumbotron">
  <h1>Edit <%= @product.name %></h1>
</div>

<%= render "layouts/product_form" %>

app/views/products/index.html.erb
<div class="jumbotron">
  <h1> Our Products </h1>
</div>
<% if @products.any? %>
<ul>
<% @products.each do |product| %>
<li><%= link_to product.name, product_path(product) %></li>
<% end %>
</ul>
<% else %>
<p>There are no products yet!</p>
<% end %>

<h3> <%= link_to "Create a product", new_product_path %> </h3>

app/views/products/new.html.erb
<%= render "layouts/product_form" %>

app/views/products/show.html.erb
<div class="jumbotron">
  <h1> <%= @product.name %> </h1>
  <h3> Produced in: <%= @product.country_of_origin %>
</div>
<div class="sub-nav">
  <h4><%= link_to "Add a review", new_product_review_path(@product) %></h4>
  <h4><%= link_to "Edit this product", edit_product_path(@product) %> </h4>
  <h4><%= link_to "Delete this product", product_path(@product),  :data => {:confirm => "Are you sure?", :method => "delete"} %></h4>
</div>
<br>

<% if @product.reviews.any? %>
  <h4>Check out what our customers are saying!</h4>

  <% @product.reviews.each do |review| %>
    <ul>
      <li>
        <%= link_to review.author, product_review_path(@product, review) %>
      </li>
    </ul>
  <% end %>
<% else %>
  <p>No reviews for this product yet!</p>
<% end %>

app/views/reviews/edit.html.erb
<div class="jumbotron">
  <h1> Edit <%= @review.author %>'s review</h1>
</div>
<%= render "layouts/review_form" %>
</div>
<button><%= link_to "back to product", product_path(@product) %></button>

app/views/reviews/index.html.erb
<div class="jumbotron">
  <h1> All Reviews </h1>
</div>
<% if @reviews.any? %>
<ul>
<% @reviews.each do |review| %>
<li><%= review.author %></li>
    <%= review.content_body %>
    <%= review.rating %>
<% end %>
</ul>
<% else %>
<p>There are no reviews yet!</p>
<% end %>

app/views/reviews/new.html.erb
<div class="jumbotron">
  <h1> New review</h1>
</div>

<%= render "layouts/review_form" %>

<button><%= link_to "back to product", product_path(@product) %></button>

app/views/reviews/show.html.erb
<div class="jumbotron">
  <h1><%= @product.name %>
  <h3> Review by: <%= @review.author %></h3>
  <h3> Rating: <%= @review.rating %></h3>
  <p><%= @review.content_body %></p>
  </div>
<button><%= link_to "back to product", product_path(@product) %></button>

app/views/users/index.html.erb
<div class="jumbotron">
  <h1> Current Users: </h1>
</div>
<% if @users.any? %>
<ul>
<% @users.each do |user| %>
<li><%= user.email  %></li>

<% if user.admin %>
<%= "This user is an admin" %>
<% else %>
<%= "This user is not an admin" %>
<% end %>

<% end %>
</ul>
<% else %>
<p>There are no users yet!</p>
<% end %>

app/views/users/new.html.erb
<h1> Sign up</h1>
<%= form_for @user do |f| %>
  <%= f.label "Email" %>
  <%= f.text_field :email %>
  <%= f.label "Password" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>